export interface MenuItem {
  id?: number;
  name: string;
  price?: number;
  category?: string;
  image?: string;
  description?: string;
  desc?: string;
}

export const menuItems: MenuItem[] = [
  { id: 1, name: 'Freddo espresso', price: 2.5, category: 'COFFEES' },
  { id: 2, name: 'Freddo cappuccino', price: 3, category: 'COFFEES' },
  { id: 3, name: 'Espresso', price: 2, category: 'COFFEES' },
  { id: 4, name: 'Cappuccino', price: 2.5, category: 'COFFEES' },
  { id: 5, name: 'Americano', price: 2.5, category: 'COFFEES' },
  { id: 6, name: 'HELLENIKOS', price: 1.5, category: 'COFFEES' },
  { id: 7, name: 'CHOCOLATE', price: 3, category: 'COFFEES' },
  { id: 8, name: 'Nescafe', price: 2, category: 'COFFEES' },
  { id: 9, name: 'NESCAFE_FRAPE', price: 2, category: 'COFFEES' },
  { id: 10, name: 'Latte', price: 3.5, category: 'COFFEES' },
  { id: 11, name: 'FILTER_COFFEE', price: 2, category: 'COFFEES' },
  { id: 12, name: 'COCOA', price: 2, category: 'COFFEES' },
  { id: 13, name: 'Macchiato', price: 2.5, category: 'COFFEES' },
  { id: 14, name: 'VIENNESE_CHOCOLATE', price: 3.5, category: 'COFFEES' },

  { id: 15, name: 'FANTA_ORANGE', price: 2.5, category: 'SOFT_DRINKS' },
  { id: 16, name: 'SPRITE', price: 2.5, category: 'SOFT_DRINKS' },
  { id: 17, name: 'FANTA_LEMON', price: 2.5, category: 'SOFT_DRINKS' },
  { id: 18, name: 'COCA_COLA', price: 2.5, category: 'SOFT_DRINKS' },
  { id: 19, name: 'COCA_COLA_ZERO', price: 2.5, category: 'SOFT_DRINKS' },
  { id: 20, name: 'PEACH_TEA', price: 2.5, category: 'SOFT_DRINKS' },
  { id: 21, name: 'LEMON_TEA', price: 2.5, category: 'SOFT_DRINKS' },
  { id: 22, name: 'GREEN_TEA', price: 2.5, category: 'SOFT_DRINKS' },
  { id: 23, name: 'RED_BULL', price: 4, category: 'SOFT_DRINKS' },
  { id: 24, name: 'SODA', price: 2.5, category: 'SOFT_DRINKS' },
  { id: 25, name: 'WATER_SMALL', price: 0.5, category: 'SOFT_DRINKS' },
  { id: 26, name: 'WATER_LARGE', price: 1, category: 'SOFT_DRINKS' },
  { id: 27, name: 'PERRIER', price: 2.5, category: 'SOFT_DRINKS' },
  { id: 28, name: 'SCHWEPPES_ORANGE', price: 2.5, category: 'SOFT_DRINKS' },
  { id: 29, name: 'SCHWEPPES_LEMON', price: 2.5, category: 'SOFT_DRINKS' },
  { id: 30, name: 'SCHWEPPES_PINK', price: 2.5, category: 'SOFT_DRINKS' },
  { id: 31, name: 'TONIC', price: 2.5, category: 'SOFT_DRINKS' },
  { id: 32, name: 'THREE_CENTS_PINK', price: 3, category: 'SOFT_DRINKS' },
  { id: 33, name: 'THREE_CENTS_GINGER', price: 3, category: 'SOFT_DRINKS' },

  { id: 40, name: 'FRESH_JUICE', price: 4, category: 'JUICES' },
  { id: 41, name: 'ORANGE_JUICE', price: 2.5, category: 'JUICES' },
  { id: 42, name: 'MIXED_JUICE', price: 2.5, category: 'JUICES' },
  { id: 43, name: 'SOUR_CHERRY_JUICE', price: 2.5, category: 'JUICES' },
  { id: 44, name: 'BANANA_JUICE', price: 2.5, category: 'JUICES' },
  { id: 45, name: 'APPLE_JUICE', price: 2.5, category: 'JUICES' },
  { id: 46, name: 'PINEAPPLE_JUICE', price: 2.5, category: 'JUICES' },
  { id: 47, name: 'APRICOT_JUICE', price: 2.5, category: 'JUICES' },
  { id: 48, name: 'PEACH_JUICE', price: 2.5, category: 'JUICES' },
  { id: 49, name: 'MANDARIN_JUICE', price: 2.5, category: 'JUICES' },
  { id: 50, name: 'STRAWBERRY_JUICE', price: 2.5, category: 'JUICES' },

  { id: 51, name: 'TOAST', price: 2.5, category: 'TOASTS_CREPS' },
  { id: 52, name: 'SAVORY_CREPE', price: 3, category: 'TOASTS_CREPS', image: 'https://21images.s3.eu-north-1.amazonaws.com/almiri.jpg' },
  { id: 53, name: 'SWEET_CREPE', price: 3.5, category: 'TOASTS_CREPS', image: 'https://21images.s3.eu-north-1.amazonaws.com/crepeglykiaa.png' },

  { id: 54, name: 'BARREL_SMALL', price: 3, category: 'BEERS' },
  { id: 55, name: 'BARREL_LARGE', price: 4, category: 'BEERS' },
  { id: 56, name: 'KAISER', price: 3, category: 'BEERS' },
  { id: 57, name: 'RADLER', price: 3, category: 'BEERS' },
  { id: 58, name: 'ALFA', price: 3, category: 'BEERS' },
  { id: 59, name: 'MYTHOS', price: 3, category: 'BEERS' },
  { id: 60, name: 'HEINEKEN', price: 3, category: 'BEERS' },
  { id: 61, name: 'AMSTEL', price: 3, category: 'BEERS' },
  { id: 62, name: 'CORONA', price: 5, category: 'BEERS' },
  { id: 63, name: 'VERGINA', price: 3, category: 'BEERS' },
  { id: 64, name: 'VERGINA_WEISS', price: 5, category: 'BEERS' },
  { id: 65, name: 'VERGINA_RED', price: 5, category: 'BEERS' },
  { id: 66, name: 'VERGINA_ZERO', price: 3, category: 'BEERS' },
  { id: 67, name: 'FIX_DARK', price: 3, category: 'BEERS' },
  { id: 68, name: 'HEINEKEN_ZERO', price: 3, category: 'BEERS' },
  { id: 69, name: 'SEVEN_SEALS', price: 4, category: 'BEERS' },

  { id: 70, name: 'DRINK_SIMPLE', price: 6, category: 'DRINKS_WINES' },
  { id: 71, name: 'DRINK_SPECIAL', price: 7, category: 'DRINKS_WINES' },
  { id: 72, name: 'DRINK_PREMIUM', price: 11, category: 'DRINKS_WINES' },
  { id: 73, name: 'WINE_GLASS', price: 5, category: 'DRINKS_WINES' },
  { id: 75, name: 'RETSINA_VASILIKI', price: 5, category: 'DRINKS_WINES' },
  { id: 79, name: 'LEIVADIOTI_BOTTLE', price: 5, category: 'DRINKS_WINES' },
  { id: 80, name: 'GORDONS_SPACE', price: 4, category: 'DRINKS_WINES' },
  { id: 81, name: 'PARANGA_BOTTLE', price: 25, category: 'DRINKS_WINES' },
  { id: 82, name: 'SAMAROPETRA_BOTTLE', price: 30, category: 'DRINKS_WINES' },

  { id: 83, name: 'Sex on the beach', price: 9, category: 'Cocktails' },
  { id: 84, name: 'Caipiroska', price: 9, category: 'Cocktails' },
  { id: 85, name: 'Daiquiri', price: 9, category: 'Cocktails' },
  { id: 86, name: 'Zombie', price: 9, category: 'Cocktails' },
  { id: 87, name: 'Mojito', price: 9, category: 'Cocktails' },
  { id: 88, name: 'Cosmopolitan', price: 9, category: 'Cocktails' },
  { id: 89, name: 'Margarita', price: 9, category: 'Cocktails' },
  { id: 90, name: 'Caipirinha', price: 9, category: 'Cocktails' },
  { id: 91, name: 'Negroni', price: 9, category: 'Cocktails' },
  { id: 92, name: 'Aperol spritz', price: 9, category: 'Cocktails' },
  { id: 93, name: 'Mai tai', price: 9, category: 'Cocktails' },
  { id: 94, name: 'Long island', price: 9, category: 'Cocktails' },
  { id: 95, name: 'Pina colada', price: 9, category: 'Cocktails' },
  { id: 96, name: 'Yuzi gun', price: 10, category: 'Cocktails', description: 'Gin, pure yuzu, lemon juice, pink grapefruit soda, cinnamon' },
  { id: 97, name: 'Cucu splash', price: 10, category: 'Cocktails', description: 'Gin, lemon juice, cucumber liquer, falernum, ginger beer' },
  { id: 98, name: 'Passion paradise', price: 10, category: 'Cocktails', description: 'Vodka, pure strawberry, pure passion fruit, lemon juice' },
  { id: 99, name: 'Green Apple Perfume', price: 10, category: 'Cocktails', description: 'White rum, green apple liquer, falernum, lemon juice' },
  { id: 100, name: "Bartender's choice", price: 9, category: 'Cocktails' },

  { id: 101, name: 'OMELETTE', price: 7, category: 'BREAKFAST', image: 'https://21images.s3.eu-north-1.amazonaws.com/omeletee.png', description: 'OMELETTE_DESC' },
  { id: 102, name: 'SCRAMBLED_EGGS', price: 6, category: 'BREAKFAST', description: 'SCRAMBLED_EGGS_DESC', image: 'https://21images.s3.eu-north-1.amazonaws.com/scrabll.png' },
  { id: 103, name: 'SCRAMBLED_EGGS_SALMON', price: 7, category: 'BREAKFAST', description: 'SCRAMBLED_EGGS_SALMON_DESC' },
  { id: 104, name: 'FRENCH_TOAST_SIMPLE', price: 5, image: 'https://21images.s3.eu-north-1.amazonaws.com/frenchtoast.png', category: 'BREAKFAST' },
  { id: 105, name: 'FRENCH_TOAST_HONEY_CINNAMON', price: 6, category: 'BREAKFAST' },
  { id: 106, name: 'PANCAKE_PRALINE', price: 7, category: 'BREAKFAST', image: 'https://21images.s3.eu-north-1.amazonaws.com/pancakee.png' },
  { id: 107, name: 'PANCAKE_HONEY_CINNAMON', price: 7, category: 'BREAKFAST', image: 'https://21images.s3.eu-north-1.amazonaws.com/french+toast+meli.png' },
  { id: 108, name: 'PANCAKE_PRALINE_BANANA_HAZELNUT', price: 9, category: 'BREAKFAST' },
  { id: 109, name: 'FRIED_EGGS_BACON', price: 6, category: 'BREAKFAST', image: 'https://21images.s3.eu-north-1.amazonaws.com/augaa.png' },
  { id: 110, name: 'YOGURT_HONEY_WALNUTS', price: 5, category: 'BREAKFAST' },
  { id: 111, name: 'YOGURT_HONEY_WALNUTS_FRUITS', price: 6, category: 'BREAKFAST', image: 'https://21images.s3.eu-north-1.amazonaws.com/giaourtii.png' },

  { id: 112, name: 'CLUB_SANDWICH', price: 9, category: 'CLUB_SANDWICH', description: 'CLUB_SANDWICH_DESC', image: 'https://21images.s3.eu-north-1.amazonaws.com/club.png' },
  { id: 113, name: 'CLUB_SANDWICH_CAESAR_CHICKEN', price: 11, category: 'CLUB_SANDWICH', description: 'CLUB_SANDWICH_CAESAR_CHICKEN_DESC' },
  { id: 114, name: 'CLUB_SANDWICH_GYRO', price: 11, category: 'CLUB_SANDWICH', description: 'CLUB_SANDWICH_GYRO_DESC', image: 'https://21images.s3.eu-north-1.amazonaws.com/gyrosclub.jpg' },
  { id: 115, name: 'CLUB_SANDWICH_PANSETSA', price: 12, category: 'CLUB_SANDWICH', image: 'https://21images.s3.eu-north-1.amazonaws.com/clubpanseta.png', description: 'CLUB_SANDWICH_PANSETSA_DESC' },

  { id: 116, name: 'JUNIOR_1', price: 7.5, category: 'JUNIOR_MENU', description: 'JUNIOR_1_DESC' },
  { id: 117, name: 'JUNIOR_2', price: 7.5, category: 'JUNIOR_MENU', description: 'JUNIOR_2_DESC' },


  { id: 122, name: 'PINSA_SIMPLE', price: 11, category: 'PINSA', image: 'https://21images.s3.eu-north-1.amazonaws.com/pinsa.png', description: 'PINSA_SIMPLE_DESC' },
  { id: 123, name: 'PINSA_MARGARITA', price: 11, category: 'PINSA', description: 'PINSA_MARGARITA_DESC' },
  { id: 124, name: 'PINSA_SPECIAL', price: 12, category: 'PINSA', description: 'PINSA_SPECIAL_DESC' },
  { id: 125, name: 'PINSA_21', price: 12, category: 'PINSA', image: 'https://21images.s3.eu-north-1.amazonaws.com/pinsaa21.png', description: 'PINSA_21_DESC' },

  { id: 126, name: 'NAPOLITANA', price: 8, category: 'PASTA', description: 'NAPOLITANA_DESC' },
  { id: 127, name: 'BOLOGNESE', price: 9, category: 'PASTA', description: 'BOLOGNESE_DESC' },
  { id: 128, name: 'CARBONARA', price: 9, category: 'PASTA', description: 'CARBONARA_DESC' },
  { id: 129, name: 'penesMeKotopoulo', price: 11, category: 'PASTA', description: 'penesMeKotopouloDesc' },
  { id: 130, name: 'rigatoniCheeses', price: 9, category: 'PASTA', description: 'rigatoniCheesesDesc' },
  { id: 131, name: 'PASTA_21', price: 9, category: 'PASTA', description: 'PASTA_21_DESC', image: 'https://21images.s3.eu-north-1.amazonaws.com/pastaa+21.png' },
  { id: 132, name: 'SHRIMP_PASTA', price: 18, category: 'PASTA', image: 'https://21images.s3.eu-north-1.amazonaws.com/garidomakaronada.png', description: 'SHRIMP_PASTA_DESC' },
  { id: 133, name: 'PAPPARDELLE_OX_TAIL', price: 16, category: 'PASTA', image: 'https://21images.s3.eu-north-1.amazonaws.com/ragouu.png', description: 'PAPPARDELLE_OX_TAIL_DESC' },
  { id: 134, name: 'RISOTI', price: 15, category: 'PASTA', description: 'RISOTI_DESC', image: 'https://21images.s3.eu-north-1.amazonaws.com/rizotiimanitaria.png' },
  { id: 135, name: 'LINGUINI_OCTOPUS', price: 18, category: 'PASTA', description: 'LINGUINI_OCTOPUS_DESC' },

  { id: 136, name: 'HOT_DOG', price: 6, category: 'HOTDOG_BURGERS', description: 'HOT_DOG_DESC' },
  { id: 137, name: 'BURGER_BBQ', price: 9, category: 'HOTDOG_BURGERS', description: 'BURGER_BBQ_DESC' },
  { id: 138, name: 'BURGER_CAESAR', price: 9, category: 'HOTDOG_BURGERS', description: 'BURGER_CAESAR_DESC' },
  { id: 139, name: 'BURGER_21', price: 10, category: 'HOTDOG_BURGERS', image: 'https://21images.s3.eu-north-1.amazonaws.com/burger.png', description: 'BURGER_21_DESC' },
  { id: 140, name: 'DOUBLE_CHEESE_BURGER', price: 10, category: 'HOTDOG_BURGERS', description: 'DOUBLE_CHEESE_BURGER_DESC', image: 'https://21images.s3.eu-north-1.amazonaws.com/burgerCheese.png' },
  { id: 141, name: 'CHICKEN_CRISPY_BURGER', price: 10, category: 'HOTDOG_BURGERS', description: 'CHICKEN_CRISPY_BURGER_DESC', image: 'https://21images.s3.eu-north-1.amazonaws.com/crispyburger.jpg' },
  { id: 142, name: 'burgerChilicrispychicken', price: 10, category: 'HOTDOG_BURGERS', description: 'burgerChilicrispychickenDesc' },
  { id: 143, name: 'doubleSmash', price: 11, category: 'HOTDOG_BURGERS', description: 'doubleSmashdesc' },
  { id: 144, name: 'miniBurgers', price: 11, category: 'HOTDOG_BURGERS', description: 'miniBurgersDesc' },

  { id: 145, name: 'SHRIMP_CHILI_BAO', price: 8, category: 'BAO_BUNS', image: 'https://21images.s3.eu-north-1.amazonaws.com/garida.png', description: 'SHRIMP_CHILI_BAO_DESC' },
  { id: 146, name: 'NUGGETS_BAO', price: 7, category: 'BAO_BUNS', image: 'https://21images.s3.eu-north-1.amazonaws.com/baogarida.png', description: 'NUGGETS_BAO_DESC' },
  { id: 147, name: 'PULLED_PORK_BAO', price: 7, category: 'BAO_BUNS', image: 'https://21images.s3.eu-north-1.amazonaws.com/pull.png', description: 'PULLED_PORK_BAO_DESC' },

  { id: 148, name: 'SALAD_CAESAR', price: 8.5, category: 'SALADS', description: 'SALAD_CAESAR_DESC' },
  { id: 149, name: 'SALAD_21', price: 8, category: 'SALADS', image: 'https://21images.s3.eu-north-1.amazonaws.com/saladd+21.png', description: 'SALAD_21_DESC' },
  { id: 150, name: 'SALAD_CAPRESE', price: 7, category: 'SALADS', description: 'SALAD_CAPRESE_DESC', image: 'https://21images.s3.eu-north-1.amazonaws.com/caprese.jpg' },
  { id: 151, name: 'SALAD_KOUKOUVAGIA', price: 8, category: 'SALADS', description: 'SALAD_KOUKOUVAGIA_DESC' },
  { id: 152, name: 'SALAD_GREEK', price: 8, category: 'SALADS', description: 'SALAD_GREEK_DESC' },
  { id: 153, name: 'CHEESE_PLATTER', price: 12, category: 'SALADS', description: 'CHEESE_PLATTER_DESC' },

  { id: 154, name: 'PORK_PANSETTO', price: 15, category: 'MAIN_COURSES', description: 'PORK_PANSETTO_DESC', image: 'https://21images.s3.eu-north-1.amazonaws.com/pansetomprizolaa.png' },
  { id: 155, name: 'TORTILLA_PORK_GYRO', price: 6, category: 'MAIN_COURSES', description: 'TORTILLA_PORK_GYRO_DESC' },
  { id: 156, name: 'CHICKEN_NUGGETS', price: 11, category: 'MAIN_COURSES', image: 'https://21images.s3.eu-north-1.amazonaws.com/nuggets.jpg', description: 'CHICKEN_NUGGETS_DESC' },
  { id: 157, name: 'CHICKEN_NUGGETS_A_LA_CREME', price: 12, category: 'MAIN_COURSES', image: 'https://21images.s3.eu-north-1.amazonaws.com/alacreme.png', description: 'CHICKEN_NUGGETS_A_LA_CREME_DESC' },
  { id: 158, name: 'FRIED_CALAMARI', price: 12, category: 'MAIN_COURSES', image: 'https://21images.s3.eu-north-1.amazonaws.com/kalamari.jpg', description: 'FRIED_CALAMARI_DESC' },
  { id: 159, name: 'SALMON_TERIYAKI', price: 18, category: 'MAIN_COURSES', image: 'https://21images.s3.eu-north-1.amazonaws.com/solomos.png', description: 'SALMON_TERIYAKI_DESC' },
  { id: 160, name: 'CHICKEN_THIGH', price: 11, category: 'MAIN_COURSES', description: 'CHICKEN_THIGH_DESC', image: 'https://21images.s3.eu-north-1.amazonaws.com/fileto+mpouti.png' },
  { id: 161, name: 'BEEF_PATTY', price: 11, category: 'MAIN_COURSES', description: 'BEEF_PATTY_DESC', image: 'https://21images.s3.eu-north-1.amazonaws.com/mpiftekiaa.png' },
  { id: 162, name: 'PORK_GYRO', price: 11, category: 'MAIN_COURSES', description: 'PORK_GYRO_DESC' },
  { id: 163, name: 'MIX_GRILL', price: 17, category: 'MAIN_COURSES', description: 'MIX_GRILL_DESC', image: 'https://21images.s3.eu-north-1.amazonaws.com/grill.jpg' },
  { id: 164, name: 'potatosCheeseBacon', price: 6, category: 'MAIN_COURSES' },

  { id: 165, name: 'Burger Λαχανικών', price: 9, category: 'LENT_MENU', description: 'BURGER_VEGETABLES_DESC' },
  { id: 166, name: 'Row No Meat Burger', price: 11, category: 'LENT_MENU', description: 'ROW_NO_MEAT_BURGER_DESC' },
  { id: 167, name: 'Napolitana', price: 8, category: 'LENT_MENU', description: 'NAPOLITANA_LENT_DESC' },
  { id: 168, name: 'Λιγκουίνι με Θαλασσινά', price: 18, category: 'LENT_MENU', description: '' },
  { id: 169, name: 'Γαριδομακαρονάδα', price: 18, category: 'LENT_MENU', description: '' },
  { id: 170, name: 'Κουκουβάγια Salad', price: 8, category: 'LENT_MENU', description: 'KOUKOUVAGIA_SALAD_LENT_DESC' },
  { id: 171, name: '21 Salad με Γαρίδες', price: 10, category: 'LENT_MENU', description: 'SALAD_21_SHRIMP_DESC' },
  { id: 172, name: 'Πέννες Salad', price: 10, category: 'LENT_MENU', description: 'PENNE_SALAD_DESC' },
  { id: 173, name: 'Pinsa Χωριάτικη', price: 12, category: 'LENT_MENU', description: 'PINSA_GREEK_LENT_DESC' },
  { id: 174, name: 'Pinsa Νηστίσιμη', price: 11, category: 'LENT_MENU', description: 'PINSA_LENTEN_DESC' },
  { id: 175, name: 'Bao Buns Γαρίδας', price: 8, category: 'LENT_MENU', description: 'BAO_BUNS_SHRIMP_LENT_DESC' },
  { id: 176, name: 'Club Καλαμάρι', price: 12, category: 'LENT_MENU', description: 'CLUB_CALAMARI_DESC' },
  { id: 177, name: 'Mix Grill', price: 18, category: 'LENT_MENU', description: 'MIX_GRILL_LENT_DESC' },
  { id: 178, name: 'Πατάτες Country', price: 6, category: 'LENT_MENU', description: 'COUNTRY_POTATOES_DESC' },

  { id: 200, name: 'BURGER_BBQ_DOUBLE_CHEESE_SOFT_DRINKS', price: 19, category: 'COMBO_OFFERS', description: 'COMBO_OFFER_1_DESC', image: 'https://21images.s3.eu-north-1.amazonaws.com/2burger.jpeg' },
  { id: 201, name: 'HOT_DOG_X2_SWEET_CREPE', price: 12, category: 'COMBO_OFFERS', description: 'COMBO_OFFER_2_DESC', image: 'https://21images.s3.eu-north-1.amazonaws.com/2hotdog.jpeg' },
  { id: 202, name: 'DOUBLE_SMASH_SOFT_DRINK_SWEET_CREPE', price: 15, category: 'COMBO_OFFERS', description: 'COMBO_OFFER_3_DESC', image: 'https://21images.s3.eu-north-1.amazonaws.com/1burger+(1).jpeg' },
];

export const SOFT_DRINKS = menuItems.filter(item => item.category === 'SOFT_DRINKS');

export const COMBO_SOFT_DRINKS = menuItems.filter(item => 
  item.category === 'SOFT_DRINKS' && 
  [15, 16, 17, 18, 19, 20, 21, 22, 24, 31].includes(item.id!)
);

export const ingredients: Array<{ name: string; price: number; selected?: boolean }> = [
  { name: 'κασέρι', price: 0.5 },
  { name: 'ζαμπόν', price: 0.5 },
  { name: 'γαλοπούλα', price: 0.5 },
  { name: 'κοτομπουκιές', price: 1 },
  { name: 'κασεροκροκέτα', price: 1 },
  { name: 'μπέικον', price: 0.5 },
  { name: 'ντομάτα', price: 0.5 },
  { name: 'αυγό', price: 0.5 },
  { name: 'φέτα', price: 0.5 },
  { name: 'μανιτάρια', price: 0.5 },
  { name: 'χτυπητή', price: 0.5 },
  { name: 'μαγιονέζα', price: 0.5 },
  { name: 'πατατάκια', price: 0.5 },
  { name: 'sauce μουστάρδας', price: 0.5 },
  { name: 'καπνιστή μπριζόλα', price: 0.5 },
  { name: 'πεπερόνι', price: 0.5 },
  { name: 'σαλάμι μπύρας', price: 0.5 },
  { name: 'μορταδέλα', price: 0.5 },
  { name: 'philadelphia', price: 0.5 },
  { name: 'πάριζα', price: 0.5 },
  { name: 'κοτόπουλο', price: 1 },
  { name: 'πιπεριά', price: 0.5 },
  { name: 'καλαμπόκι', price: 0.5 },
  { name: 'ελιές', price: 0.5 },
  { name: 'ρωσική', price: 0.5 },
  { name: 'πατάτες τηγανητές', price: 1 },
  { name: 'ουγγαρέζα', price: 0.5 },
  { name: 'κηπουρού', price: 0.5 },
  { name: 'πάπρικα', price: 0.5 },
  { name: 'μανούρι', price: 0.5 },
  { name: 'λουκάνικο', price: 1 },
  { name: 'σαλάμι αέρος', price: 0.5 }
];

export const sweetIngredients: Array<{ name: string; price: number; selected?: boolean }> = [
  { name: 'Μερέντα', price: 0.5 },
  { name: 'Nutella', price: 1 },
  { name: 'Μπισκότο', price: 0.5 },
  { name: 'Μπανάνα', price: 0.5 },
  { name: 'Λευκή Πραλίνα', price: 0.5 },
  { name: 'Bueno Πραλίνα', price: 0.5 },
  { name: 'Φράουλα Πραλίνα', price: 0.5 },
  { name: 'Παγωτό', price: 2.5 },
  { name: 'Μπισκότο Oreo', price: 0.5 },
  { name: 'Φράουλα Κομματάκια', price: 1 },
  { name: 'Bueno Κομματάκια', price: 1 },
  { name: 'Καρύδι', price: 0.5 },
  { name: 'Φουντούκι', price: 0.5 },
  { name: 'Αμύγδαλο', price: 0.5 },
  { name: 'Lila pause', price: 1.5 },
  { name: 'Μαρμελάδα φράουλα', price: 0.5 },
  { name: 'Μαρμελάδα ροδάκινο', price: 0.5 },
  { name: 'Caprice', price: 1 }
];
